[project]
name = 'parametric-insurance-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.oracle-processor]
path = 'contracts/oracle-processor.clar'
clarity_version = 2
epoch = 2.5

[contracts.policy-manager]
path = 'contracts/policy-manager.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
